### ISSUE TITLE
Support for optional fields

### ISSUE THREAD

**Issue by harkamals** [srikrsna/protoc-gen-gotag#35] opened 2022-09-17 16:03 UTC
go generate ./...
api/assessment/metric.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-gotag hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--gotag_out: 
proto.go:38: running "protoc": exit status 1

**Comment by Kavuti** [comment] 2024-05-10 12:38
Is this issue still relevant? 
Me, @ucpr and @mesmerx are embracing the project and planning both maintenance and evolution, so we would like to tidy up everything before working on new features. If the issue is not relevant anymore or we don't get a response in a few days, it will be closed, until we are ready to work on it.

**Comment by tristan-vt** [comment] 2024-05-22 09:50
Hi! We are definitely still interested in this functionality. I feel like it should mainly be just updating proto version

**Comment by Kavuti** [comment] 2024-05-27 20:18
Which version of the library are you using? Seems that the plugin supports the `optional` fields since the Jun 16, 2021 release. Maybe you didn't upgrade to the latest version?

**Comment by mesmerx** [comment] 2024-06-01 01:15
if you want optional for a "null" field in proto3 all fields are optional in that sense, so it dont make sense, in proto itself, if its oneof its other case

https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3

**Comment by oxisto** [comment] 2024-06-08 07:45
This should be fixed with https://github.com/srikrsna/protoc-gen-gotag/pull/48

**Closed** 2024-06-08 15:39 UTC
